import { render, screen, act, fireEvent } from '@testing-library/react'
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { HoldToRelease } from '../HoldToRelease'

describe('HoldToRelease', () => {
  beforeEach(() => vi.useFakeTimers())
  afterEach(() => vi.useRealTimers())

  it('fires onComplete once after a full hold', () => {
    const onComplete = vi.fn()
    render(<HoldToRelease onComplete={onComplete} />)
    fireEvent.pointerDown(screen.getByRole('button'))
    act(() => vi.advanceTimersByTime(1100))
    expect(onComplete).toHaveBeenCalledOnce()
    act(() => vi.advanceTimersByTime(1100))
    expect(onComplete).toHaveBeenCalledOnce()
  })
  it('resets when released early', () => {
    const onComplete = vi.fn()
    render(<HoldToRelease onComplete={onComplete} />)
    const btn = screen.getByRole('button')
    fireEvent.pointerDown(btn)
    act(() => vi.advanceTimersByTime(500))
    fireEvent.pointerUp(btn)
    act(() => vi.advanceTimersByTime(1000))
    expect(onComplete).not.toHaveBeenCalled()
    expect(screen.getByTestId('hold-fill').style.width).toBe('0%')
  })
  it('does nothing when disabled', () => {
    const onComplete = vi.fn()
    render(<HoldToRelease disabled onComplete={onComplete} />)
    fireEvent.pointerDown(screen.getByRole('button'))
    act(() => vi.advanceTimersByTime(1500))
    expect(onComplete).not.toHaveBeenCalled()
  })
  it('stops and resets if disabled flips true mid-hold', () => {
    const onComplete = vi.fn()
    const { rerender } = render(<HoldToRelease onComplete={onComplete} />)
    const btn = screen.getByRole('button')
    fireEvent.pointerDown(btn)
    act(() => vi.advanceTimersByTime(500))
    rerender(<HoldToRelease disabled onComplete={onComplete} />)
    act(() => vi.advanceTimersByTime(1000))
    expect(onComplete).not.toHaveBeenCalled()
    expect(screen.getByTestId('hold-fill').style.width).toBe('0%')
  })
  it('stops on pointer cancel mid-hold', () => {
    const onComplete = vi.fn()
    render(<HoldToRelease onComplete={onComplete} />)
    const btn = screen.getByRole('button')
    fireEvent.pointerDown(btn)
    act(() => vi.advanceTimersByTime(500))
    fireEvent.pointerCancel(btn)
    act(() => vi.advanceTimersByTime(1000))
    expect(onComplete).not.toHaveBeenCalled()
    expect(screen.getByTestId('hold-fill').style.width).toBe('0%')
  })
  it('does not double-fire or shorten the hold on a second pointerdown mid-hold', () => {
    const onComplete = vi.fn()
    render(<HoldToRelease onComplete={onComplete} />)
    const btn = screen.getByRole('button')
    fireEvent.pointerDown(btn)
    act(() => vi.advanceTimersByTime(500))
    fireEvent.pointerDown(btn)
    act(() => vi.advanceTimersByTime(400))
    expect(onComplete).not.toHaveBeenCalled()
    act(() => vi.advanceTimersByTime(200))
    expect(onComplete).toHaveBeenCalledOnce()
  })
  it('re-arms after a disabled→enabled cycle: retry hold fires again', () => {
    const onComplete = vi.fn()
    const { rerender } = render(<HoldToRelease onComplete={onComplete} />)
    const btn = screen.getByRole('button')
    fireEvent.pointerDown(btn)
    act(() => vi.advanceTimersByTime(1100))
    expect(onComplete).toHaveBeenCalledOnce()

    rerender(<HoldToRelease disabled onComplete={onComplete} />)
    rerender(<HoldToRelease onComplete={onComplete} />)

    fireEvent.pointerDown(btn)
    act(() => vi.advanceTimersByTime(1100))
    expect(onComplete).toHaveBeenCalledTimes(2)
  })
  it('a rerender without a disabled cycle still cannot double-fire', () => {
    const onComplete = vi.fn()
    const { rerender } = render(<HoldToRelease onComplete={onComplete} />)
    const btn = screen.getByRole('button')
    fireEvent.pointerDown(btn)
    act(() => vi.advanceTimersByTime(1100))
    expect(onComplete).toHaveBeenCalledOnce()

    rerender(<HoldToRelease onComplete={onComplete} />)
    fireEvent.pointerDown(btn)
    act(() => vi.advanceTimersByTime(1100))
    expect(onComplete).toHaveBeenCalledOnce()
  })
  it('fires nothing after unmount mid-hold', () => {
    const onComplete = vi.fn()
    const { unmount } = render(<HoldToRelease onComplete={onComplete} />)
    fireEvent.pointerDown(screen.getByRole('button'))
    act(() => vi.advanceTimersByTime(500))
    unmount()
    act(() => vi.advanceTimersByTime(1000))
    expect(onComplete).not.toHaveBeenCalled()
  })

  describe('keyboard path', () => {
    it('fires onComplete once after holding Space for the full duration', () => {
      const onComplete = vi.fn()
      render(<HoldToRelease onComplete={onComplete} />)
      const btn = screen.getByRole('button')
      fireEvent.keyDown(btn, { key: ' ' })
      act(() => vi.advanceTimersByTime(1100))
      expect(onComplete).toHaveBeenCalledOnce()
      act(() => vi.advanceTimersByTime(1100))
      expect(onComplete).toHaveBeenCalledOnce()
    })
    it('fires onComplete once after holding Enter for the full duration', () => {
      const onComplete = vi.fn()
      render(<HoldToRelease onComplete={onComplete} />)
      const btn = screen.getByRole('button')
      fireEvent.keyDown(btn, { key: 'Enter' })
      act(() => vi.advanceTimersByTime(1100))
      expect(onComplete).toHaveBeenCalledOnce()
    })
    it('resets when Space is released early (keyup)', () => {
      const onComplete = vi.fn()
      render(<HoldToRelease onComplete={onComplete} />)
      const btn = screen.getByRole('button')
      fireEvent.keyDown(btn, { key: ' ' })
      act(() => vi.advanceTimersByTime(500))
      fireEvent.keyUp(btn, { key: ' ' })
      act(() => vi.advanceTimersByTime(1000))
      expect(onComplete).not.toHaveBeenCalled()
      expect(screen.getByTestId('hold-fill').style.width).toBe('0%')
    })
    it('resets on blur mid-hold', () => {
      const onComplete = vi.fn()
      render(<HoldToRelease onComplete={onComplete} />)
      const btn = screen.getByRole('button')
      fireEvent.keyDown(btn, { key: ' ' })
      act(() => vi.advanceTimersByTime(500))
      fireEvent.blur(btn)
      act(() => vi.advanceTimersByTime(1000))
      expect(onComplete).not.toHaveBeenCalled()
      expect(screen.getByTestId('hold-fill').style.width).toBe('0%')
    })
    it('ignores repeat keydown events and does not start a hold on its own', () => {
      const onComplete = vi.fn()
      render(<HoldToRelease onComplete={onComplete} />)
      const btn = screen.getByRole('button')
      fireEvent.keyDown(btn, { key: ' ', repeat: true })
      fireEvent.keyDown(btn, { key: ' ', repeat: true })
      fireEvent.keyDown(btn, { key: ' ', repeat: true })
      act(() => vi.advanceTimersByTime(1500))
      expect(onComplete).not.toHaveBeenCalled()
      expect(screen.getByTestId('hold-fill').style.width).toBe('0%')
    })
    it('does nothing on keydown when disabled', () => {
      const onComplete = vi.fn()
      render(<HoldToRelease disabled onComplete={onComplete} />)
      const btn = screen.getByRole('button')
      fireEvent.keyDown(btn, { key: ' ' })
      act(() => vi.advanceTimersByTime(1500))
      expect(onComplete).not.toHaveBeenCalled()
    })
    it('ignores keys other than Space and Enter', () => {
      const onComplete = vi.fn()
      render(<HoldToRelease onComplete={onComplete} />)
      const btn = screen.getByRole('button')
      fireEvent.keyDown(btn, { key: 'a' })
      act(() => vi.advanceTimersByTime(1500))
      expect(onComplete).not.toHaveBeenCalled()
    })
  })

  describe('cross-input interleave', () => {
    it('resets when a hold started by pointerdown is stopped by keyup Space mid-hold', () => {
      const onComplete = vi.fn()
      render(<HoldToRelease onComplete={onComplete} />)
      const btn = screen.getByRole('button')
      fireEvent.pointerDown(btn)
      act(() => vi.advanceTimersByTime(500))
      fireEvent.keyUp(btn, { key: ' ' })
      act(() => vi.advanceTimersByTime(1000))
      expect(onComplete).not.toHaveBeenCalled()
      expect(screen.getByTestId('hold-fill').style.width).toBe('0%')
    })
    it('resets when a hold started by keydown Space is stopped by pointerup mid-hold', () => {
      const onComplete = vi.fn()
      render(<HoldToRelease onComplete={onComplete} />)
      const btn = screen.getByRole('button')
      fireEvent.keyDown(btn, { key: ' ' })
      act(() => vi.advanceTimersByTime(500))
      fireEvent.pointerUp(btn)
      act(() => vi.advanceTimersByTime(1000))
      expect(onComplete).not.toHaveBeenCalled()
      expect(screen.getByTestId('hold-fill').style.width).toBe('0%')
    })
  })
})
